openapi: 3.0.0
info:
  version: "1.0.0"
  title: "FilesArray"


paths:
  /Files:
    post:
      responses:
        "200":
          description: "sample"
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    nullable: true
                    anyOf:
                      - $ref: "#/components/schemas/Files"
components:
  schemas:
    Files:
      type: object
      properties:
        files:
          type: array
          items:
            type: string
            format: binary
