openapi: "3.0.0"
info:
  title: "simple"
  version: "1.0"
paths:
  /file/{id}/upload:
    post:
      parameters: 
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID
        - in: query
          name: path
          schema:
            type: string
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '204':
          description: No Content
  /user/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: The user ID
    get:
      responses:
        202:
          description: "accept"
    patch:
      summary: Updates an existing user with the specified ID
      responses:
        202:
          description: "accept"
    delete:
      summary: Deletes the user with the specified ID
      responses:
        202:
          description: "accept"
  /user/{id}/abc:
    get:
      parameters: 
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: The user ID
        - in: query
          name: q
          schema:
            type: string
      responses:
        202:
          description: "accept"
  /user/{id}/xyz:
    parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
        description: The user ID
    get:
      responses:
        202:
          description: "accept"
    put:
      responses:
        202:
          description: "accept"
  /dummy/{id}/simple:
    put:
      summary: "simple"
      parameters:
        - name: "id"
          in: "path"
          description: "id"
          required: true
          schema:
            type: "integer"
      responses:
        202:
          description: "accept"
  /dummy/{id}/query:
    put:
      summary: "query"
      parameters:
        - name: "id"
          in: "path"
          description: "id"
          required: true
          schema:
            type: "integer"
        - name: "q"
          in: "query"
          description: "query"
          schema:
            type: "string"
      responses:
        202:
          description: "accept"
  /dummy/{id}/content:
    put:
      summary: "ng"
      parameters:
        - name: "id"
          in: "path"
          description: "id"
          required: true
          schema:
            type: "integer"
      responses:
        202:
          description: "accept"
          content:
            application/json:
              schema:
                type: "string"
components:
  schemas:
    Customer:
      description: Customer
      properties:
        id:
          description: ID
          type: integer
        name:
          description: NAME
          type: string
        pet:
          description: 'Type of pet 1:dog 2:cat 3:other'
          type: number
          enum:
            - 1
            - 2
            - 3
