name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    name: "Test on Node:${{ matrix.node-version }} OS:${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # node-version: [12, 14, 16]
        node-version: [12]
        os: [ubuntu-latest]
        # include:
        #   - os: windows-latest
        #     node-version: 14
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-node-v${{ matrix.node-version }}-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile
        if: steps.yarn-cache.outputs.cache-hit != 'true'
      - run: yarn lint
        if: matrix.os != 'windows-latest'
      - run: yarn typecheck
      - run: yarn test --coverage
      - name: Debug
        if: ${{ always() }}
        uses: mxschmitt/action-tmate@v3
      - run: npx codecov
        if: github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest' && matrix.node-version == 14
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
